### PR TITLE
Extend health report

### PR DESCRIPTION
**Pull request by adamtickner**
Issue link: https://github.com/microsoft/service-fabric-observer/issues/85

I have run the Fabric Observer tests.

### CODE REVIEW

**Comment by adamtickner** [comment]
It looks like there are some commit differences between master and develop, please let me know if I need to make any changes and I'll fix up.

**Comment by adamtickner** [comment]
I've also just seen there is HealthReportKind in System.Fabric.Health - but it is a larger change to switch to this enum and would be a breaking change.

**Comment by GitTorre** [comment]
Thanks. I am evaluating this. 

Note the differences between branches has been resolved. Thank you for spotting that. In general, develop is where development takes place (and it lagged in Readme, not code).

**Comment by GitTorre** [comment]
This seems benign enough to me and will not break existing code.

**Pull request merged**
